/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    copy: typeof import('./../components/editor copy.vue')['default'];
    CustomDialog: typeof import('./../components/customDialog.vue')['default'];
    Dialog: typeof import('./../components/dialog.vue')['default'];
    Editor: typeof import('./../components/editor.vue')['default'];
    ElAside: typeof import('element-plus/es')['ElAside'];
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb'];
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem'];
    ElButton: typeof import('element-plus/es')['ElButton'];
    ElCard: typeof import('element-plus/es')['ElCard'];
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider'];
    ElContainer: typeof import('element-plus/es')['ElContainer'];
    ElDialog: typeof import('element-plus/es')['ElDialog'];
    ElDropdown: typeof import('element-plus/es')['ElDropdown'];
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem'];
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu'];
    ElForm: typeof import('element-plus/es')['ElForm'];
    ElFormItem: typeof import('element-plus/es')['ElFormItem'];
    ElHeader: typeof import('element-plus/es')['ElHeader'];
    ElIcon: typeof import('element-plus/es')['ElIcon'];
    ElInput: typeof import('element-plus/es')['ElInput'];
    ElMain: typeof import('element-plus/es')['ElMain'];
    ElMenu: typeof import('element-plus/es')['ElMenu'];
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem'];
    ElOption: typeof import('element-plus/es')['ElOption'];
    ElPagination: typeof import('element-plus/es')['ElPagination'];
    ElPopover: typeof import('element-plus/es')['ElPopover'];
    ElSelect: typeof import('element-plus/es')['ElSelect'];
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu'];
    ElSwitch: typeof import('element-plus/es')['ElSwitch'];
    ElTable: typeof import('element-plus/es')['ElTable'];
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn'];
    HelloWorld: typeof import('./../components/HelloWorld.vue')['default'];
    Layout: typeof import('./../layout/index.vue')['default'];
    LeftMode: typeof import('./../layout/leftMode.vue')['default'];
    LeftTopMode: typeof import('./../layout/leftTopMode.vue')['default'];
    Menu: typeof import('./../components/layout/menu.vue')['default'];
    Navigator: typeof import('./../layout/components/navigator.vue')['default'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
    SideBar: typeof import('./../layout/components/sideBar/index.vue')['default'];
    SideBarItem: typeof import('./../layout/components/sideBar/sideBarItem.vue')['default'];
    SvgIcon: typeof import('./../components/SvgIcon.vue')['default'];
    TopBar: typeof import('./../layout/components/topBar.vue')['default'];
    TopMode: typeof import('./../layout/topMode.vue')['default'];
    UstomDialog: typeof import('./../components/ustomDialog.vue')['default'];
    YamlEditor: typeof import('./../components/yamlEditor.vue')['default'];
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective'];
  }
}
